
package cz.nuc.wheelgo.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import org.jinouts.xml.namespace.QName;
import org.jinouts.jws.WebMethod;
import org.jinouts.jws.WebParam;
import org.jinouts.jws.WebResult;
import org.jinouts.jws.WebService;
import org.jinouts.xml.bind.annotation.XmlSeeAlso;
import org.jinouts.xml.ws.Action;
import org.jinouts.xml.ws.RequestWrapper;
import org.jinouts.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2013-04-17T17:26:18.682+02:00
 * Generated source version: 2.6.5
 * 
 */
public final class WheelGoService_WheelGoServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://service/", "WheelGoService");

    private WheelGoService_WheelGoServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = WheelGoService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WheelGoService_Service ss = new WheelGoService_Service(wsdlURL, SERVICE_NAME);
        WheelGoService port = ss.getWheelGoServicePort();  
        
        {
        System.out.println("Invoking getImage...");
        int _getImage_arg0 = 0;
        cz.nuc.wheelgo.service.PhotoDTO _getImage__return = port.getImage(_getImage_arg0);
        System.out.println("getImage.result=" + _getImage__return);


        }
        {
        System.out.println("Invoking addProblem...");
        cz.nuc.wheelgo.service.ProblemDTO _addProblem_arg0 = null;
        Integer _addProblem__return = port.addProblem(_addProblem_arg0);
        System.out.println("addProblem.result=" + _addProblem__return);


        }
        {
        System.out.println("Invoking editPlace...");
        cz.nuc.wheelgo.service.PlaceDTO _editPlace_arg0 = null;
        Integer _editPlace__return = port.editPlace(_editPlace_arg0);
        System.out.println("editPlace.result=" + _editPlace__return);


        }
        {
        System.out.println("Invoking navigate...");
        cz.nuc.wheelgo.service.Location _navigate_arg0 = null;
        cz.nuc.wheelgo.service.Location _navigate_arg1 = null;
        java.util.List<cz.nuc.wheelgo.service.Node> _navigate__return = port.navigate(_navigate_arg0, _navigate_arg1);
        System.out.println("navigate.result=" + _navigate__return);


        }
        {
        System.out.println("Invoking getPlaceDetail...");
        Integer _getPlaceDetail_arg0 = null;
        cz.nuc.wheelgo.service.PlaceDTO _getPlaceDetail__return = port.getPlaceDetail(_getPlaceDetail_arg0);
        System.out.println("getPlaceDetail.result=" + _getPlaceDetail__return);


        }
        {
        System.out.println("Invoking addPlace...");
        cz.nuc.wheelgo.service.PlaceDTO _addPlace_arg0 = null;
        Integer _addPlace__return = port.addPlace(_addPlace_arg0);
        System.out.println("addPlace.result=" + _addPlace__return);


        }
        {
        System.out.println("Invoking getTipDetail...");
        Integer _getTipDetail_arg0 = null;
        cz.nuc.wheelgo.service.TipDTO _getTipDetail__return = port.getTipDetail(_getTipDetail_arg0);
        System.out.println("getTipDetail.result=" + _getTipDetail__return);


        }
        {
        System.out.println("Invoking getReport...");
        Integer _getReport_arg0 = null;
        cz.nuc.wheelgo.service.ReportDTO _getReport__return = port.getReport(_getReport_arg0);
        System.out.println("getReport.result=" + _getReport__return);


        }
        {
        System.out.println("Invoking addTip...");
        cz.nuc.wheelgo.service.TipDTO _addTip_arg0 = null;
        Integer _addTip__return = port.addTip(_addTip_arg0);
        System.out.println("addTip.result=" + _addTip__return);


        }
        {
        System.out.println("Invoking editTip...");
        cz.nuc.wheelgo.service.TipDTO _editTip_arg0 = null;
        Integer _editTip__return = port.editTip(_editTip_arg0);
        System.out.println("editTip.result=" + _editTip__return);


        }
        {
        System.out.println("Invoking getProblemDetail...");
        Integer _getProblemDetail_arg0 = null;
        cz.nuc.wheelgo.service.ProblemDTO _getProblemDetail__return = port.getProblemDetail(_getProblemDetail_arg0);
        System.out.println("getProblemDetail.result=" + _getProblemDetail__return);


        }
        {
        System.out.println("Invoking deleteSpot...");
        int _deleteSpot_arg0 = 0;
        Integer _deleteSpot__return = port.deleteSpot(_deleteSpot_arg0);
        System.out.println("deleteSpot.result=" + _deleteSpot__return);


        }
        {
        System.out.println("Invoking editProblem...");
        cz.nuc.wheelgo.service.ProblemDTO _editProblem_arg0 = null;
        Integer _editProblem__return = port.editProblem(_editProblem_arg0);
        System.out.println("editProblem.result=" + _editProblem__return);


        }
        {
        System.out.println("Invoking getReportsAround...");
        cz.nuc.wheelgo.service.Location _getReportsAround_arg0 = null;
        double _getReportsAround_arg1 = 0.0;
        java.util.List<cz.nuc.wheelgo.service.ReportDTO> _getReportsAround__return = port.getReportsAround(_getReportsAround_arg0, _getReportsAround_arg1);
        System.out.println("getReportsAround.result=" + _getReportsAround__return);


        }

        System.exit(0);
    }

}
