package cz.nuc.wheelgo.service;

import java.net.MalformedURLException;
import java.net.URL;
import org.jinouts.xml.namespace.QName;
import org.jinouts.xml.ws.WebEndpoint;
import org.jinouts.xml.ws.WebServiceClient;
import org.jinouts.xml.ws.WebServiceFeature;
import org.jinouts.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2013-04-17T17:26:18.732+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebServiceClient(name = "WheelGoService", 
                  wsdlLocation = "http://192.168.1.2:8080/WheelGoService/WheelGoService?WSDL",
                  targetNamespace = "http://service/") 
public class WheelGoService_Service extends org.jinouts.ws.JinosService {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service/", "WheelGoService");
    public final static QName WheelGoServicePort = new QName("http://service/", "WheelGoServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.1.2:8080/WheelGoService/WheelGoService?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WheelGoService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.1.2:8080/WheelGoService/WheelGoService?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public WheelGoService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WheelGoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WheelGoService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns WheelGoService
     */
    @WebEndpoint(name = "WheelGoServicePort")
    public WheelGoService getWheelGoServicePort() {
        return super.getPort(WheelGoServicePort, WheelGoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WheelGoService
     */
    @WebEndpoint(name = "WheelGoServicePort")
    public WheelGoService getWheelGoServicePort(WebServiceFeature... features) {
        return super.getPort(WheelGoServicePort, WheelGoService.class, features);
    }

}
